apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: ClusterIP
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: api-gateway
