apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: datanode1
  name: datanode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        app: datanode1
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
          envFrom:
            - configMapRef:
                name: env
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          name: datanode1
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: hadoop-datanode1
      restartPolicy: Always
      volumes:
        - name: hadoop-datanode1
          persistentVolumeClaim:
            claimName: hadoop-datanode1
