apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hadoop-namenode
  name: hadoop-namenode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
