apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:4.4-community
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          env:
            - name: NEO4J_AUTH
              value: "neo4j/password"
            - name: NEO4J_server_config_strict_validation_enabled
              value: "false"
      restartPolicy: Always

