apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: api-composer
  name: api-composer
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    app: api-composer
