apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hadoop-datanode1
  name: hadoop-datanode1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
