apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-express-data
  name: mongo-express-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
