apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: namenode
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        app: namenode
    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: test
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:8020
          envFrom:
            - configMapRef:
                name: env
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          name: namenode
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
            - containerPort: 8200
              protocol: TCP
            - containerPort: 8020
              protocol: TCP
          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: hadoop-namenode
      restartPolicy: Always
      volumes:
        - name: hadoop-namenode
          persistentVolumeClaim:
            claimName: hadoop-namenode
