apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: notifications-server
  name: notifications-server
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8004
  selector:
    app: notifications-server
