apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: tasks-server
  name: tasks-server
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    app: tasks-server
